#!/bin/bash
#
# A script to set NIC MACs on the NanoPi boards.

# Thanks OpenWRT for these functions!

macaddr_add() {
	local mac=$1
	local val=$2
	local oui=${mac%:*:*:*}
	local nic=${mac#*:*:*:}

	nic=$(printf "%06x" $((0x${nic//:/} + val & 0xffffff)) | sed 's/^\(.\{2\}\)\(.\{2\}\)\(.\{2\}\)/\1:\2:\3/')
	echo $oui:$nic
}

get_mac_binary() {
	local path="$1"
	local offset="$2"

	if ! [ -e "$path" ]; then
		echo "get_mac_binary: file $path not found!" >&2
		return
	fi

	hexdump -v -n 6 -s $offset -e '5/1 "%02x:" 1/1 "%02x"' $path 2>/dev/null
}

macaddr_setbit() {
	local mac=$1
	local bit=${2:-0}

	[ $bit -gt 0 -a $bit -le 48 ] || return

	printf "%012x" $(( 0x${mac//:/} | 2**(48-bit) )) | sed -e 's/\(.\{2\}\)/\1:/g' -e 's/:$//'
}

macaddr_setbit_la() {
	macaddr_setbit $1 7
}

macaddr_unsetbit_mc() {
	local mac=$1

	printf "%02x:%s" $((0x${mac%%:*} & ~0x01)) ${mac#*:}
}

macaddr_random() {
	local randsrc=$(get_mac_binary /dev/urandom 0)

	echo "$(macaddr_unsetbit_mc "$(macaddr_setbit_la "${randsrc}")")"
}

board_name=$(strings /proc/device-tree/compatible | head -1)

case ${board_name} in
friendlyarm,nanopi-neo3)
	eth0_mac=$(get_mac_binary "/sys/bus/i2c/devices/0-0051/eeprom" 0xfa)
	if ! grep -q "$eth0_mac" /sys/class/net/eth0/address; then
		ip link set dev eth0 address $eth0_mac
	fi
	;;
friendlyarm,nanopi-r2s)
  # Some boards have an i2c, and some do not
	if [ -e "/sys/bus/i2c/devices/0-0051/eeprom" ]; then
		base_mac=$(get_mac_binary "/sys/bus/i2c/devices/0-0051/eeprom" 0xfa)
	else
		if ! [ -e "/etc/.macaddr" ]; then
			echo -n "$(macaddr_random)" > /etc/.macaddr
		fi
		base_mac=$(cat /etc/.macaddr)
	fi
	eth0_mac=$base_mac
	eth1_mac=$(macaddr_add $base_mac 1)
	if ! grep -q "$eth0_mac" /sys/class/net/eth0/address; then
		ip link set dev eth0 address $eth0_mac
	fi
	# If our eth1 does not exist yet, bring it up!
	if [ ! -d "/sys/class/net/eth1" ]; then
		modprobe r8152
	fi
	if ! grep -q "$eth1_mac" /sys/class/net/eth1/address; then
		ip link set dev eth1 address $eth1_mac
	fi
	# Do LED Setup
	modprobe ledtrig-netdev
	for ledname in nanopi-r2s:green:wan nanopi-r2s:green:lan; do
		echo "netdev" > /sys/class/leds/$ledname/trigger
		echo "1" > /sys/class/leds/$ledname/link
		echo "1" > /sys/class/leds/$ledname/tx
		echo "1" > /sys/class/leds/$ledname/rx
	done
	echo "eth0" > /sys/class/leds/nanopi-r2s:green:wan/device_name
	echo "eth1" > /sys/class/leds/nanopi-r2s:green:lan/device_name
	;;
esac
