#!/bin/bash
#
# A script to set NIC MACs on the NanoPi boards.

# Thanks OpenWRT for these functions!

macaddr_add() {
	local mac=$1
	local val=$2
	local oui=${mac%:*:*:*}
	local nic=${mac#*:*:*:}

	nic=$(printf "%06x" $((0x${nic//:/} + val & 0xffffff)) | sed 's/^\(.\{2\}\)\(.\{2\}\)\(.\{2\}\)/\1:\2:\3/')
	echo $oui:$nic
}

get_mac_binary() {
	local path="$1"
	local offset="$2"

	if ! [ -e "$path" ]; then
		echo "get_mac_binary: file $path not found!" >&2
		return
	fi

	hexdump -v -n 6 -s $offset -e '5/1 "%02x:" 1/1 "%02x"' $path 2>/dev/null
}

board_name=$(strings /proc/device-tree/compatible | head -1)

case ${board_name} in
friendlyelec,nanopi-neo3)
	eth0_mac=$(get_mac_binary "/sys/bus/i2c/devices/0-0051/eeprom" 0xfa)
	if ! grep -q "$eth0_mac" /sys/class/net/eth0/address; then
		ip link set dev eth0 address $eth0_mac
	fi
esac
