#!/bin/bash

echo "Starting 001-bootstrap within chroot!"

export DEBIAN_FRONTEND=noninteractive

# Attempt to fix slow bootstrap
ulimit -n 1024

# Conf debconf
debconf-set-selections /debconf.set
rm -f /debconf.set

# Initial package install
apt-get clean
apt-get update
apt-get -y install git binutils ca-certificates e2fsprogs haveged parted curl \
locales console-common openssh-server less vim net-tools initramfs-tools \
wireguard-tools u-boot-tools locales wget 

# Locale gen
locale-gen

# Setup root PW
echo "root:debian" | chpasswd

# Allow root SSH login with PW
sed -i 's|#PermitRootLogin prohibit-password|PermitRootLogin yes|g' /etc/ssh/sshd_config

# Install custom packages of fun
dpkg -i /root/kernel/linux-*.deb
export KMOD_PATH=$(find /lib/modules/ -maxdepth 1 | sort | tail -1)
export KERN_VERSION=$(echo ${KMOD_PATH} | xargs basename )

# Setup boot partition
mkdir -p /boot/rockchip
mv /root/kernel/*.dtb /boot/rockchip/
sed -i "s|KERNELVER|${KERN_VERSION}|g" /boot/boot.cmd
mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
cp /boot/vmlinuz-${KERN_VERSION}* /boot/Image.gz
gunzip /boot/Image.gz
cp /boot/initrd.img-${KERN_VERSION}* /boot/initramfs.cpio.gz

# Cleanup stuff we don't want floating around
apt-get autoclean
apt-get --purge -y autoremove
systemctl stop ssh.service
systemctl enable first-boot.service
rm -f /etc/ssh/ssh_host_*
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
rm -rf /boot.bak
rm -rf /root/kernel
